### PR TITLE
[WIP] Use forms for sending non-GET request.

### PR DESCRIPTION
**Pull request by ramhoj**
This PR breaks styling :(.

### CODE REVIEW

**Comment by jensljungblad** [comment]
Any ideas on how to best un-break it? :smile: 

Also, what are the reasons for doing this? Is it purely semantic or are there other reasons as well?

**Comment by ramhoj** [comment]
RackTest ;)

**Comment by jensljungblad** [comment]
Yeah I agree it's a better way to send the request, but if it's super-tricky to style it might not be worth it

**Comment by Linuus** [comment]
Just to be picky. Browsers don't support the other HTTP verbs natively. When using a form in Rails it's always a GET or a POST. The form includes the magic `_method` hidden input to make Rails (Rack?) interpret it as the correct HTTP verb (but it's not). So, the only way to get verbs other than GET and POST natively, is to use javascript :)

But sure, if someone wants to style it, go ahead. I'm all for relying on less JS. But to actually use Godmin you need JS anyway (batch actions, destroy buttons, button groups, navbar dropdowns, responsive nacbar, active navbar items....). Some of it should already work OK even with no JS but not everything.

¯\\_(ツ)_/¯

My point is not that this is a bad idea, but if we decide to do this, we should fix all the other buttons and cruft relying on JS too :) Not in this PR of course, but we should create an issue for it and work toward it and make sure godmin works fine without JS overall.

**Comment by jensljungblad** [comment]
I don't really care either way :) However, I looked into styling this and it's currently not possible with Bootstrap 3. If we really want this perhaps we could get a fix into Bootstrap 4. But for now it cannot be done if we still want the button groups.

Personally I don't think it's worth pursuing a JS-free version of Godmin. Feels perfectly reasonable to me that an admin backend application would require JS.

**Comment by ramhoj** [comment]
The way I see it you're forcing the users of the gem to depend on large and complex libraries in order to acceptance test their application. Their acceptance tests also becomes slower. This is fine for features that are hard or impractical to implement without javascript but depending on thousands of lines of code in many abstraction layers instead of adding a few lines of CSS seems odd to me.

**Comment by jensljungblad** [comment]
Oh, when you say dependencies you're talking about adding stuff like javascript drivers to capybara etc? If so that's a good point. Although I'm not sure anyone would write their their own tests for functionality provided by the gem, as it's already tested.

Speaking of which, this is a bit weird: https://github.com/varvet/godmin/blob/master/test/integration/crud_test.rb#L54

The delete link seems to work even without enabling the javascript driver for the test..?

**Comment by Linuus** [comment]
That is weird... We don't set the js driver when signing out either.

https://github.com/varvet/godmin/blob/master/test/integration/authentication_test.rb

Odd 😊

**Comment by jensljungblad** [comment]
Apparently capybara has code that detects the `data-method` attribute: https://github.com/jnicklas/capybara/blob/2a51b817b355f6c1a5e95a471a87f1a492562e55/lib/capybara/rack_test/node.rb#L56

**Comment by Linuus** [comment]
Ah, that explains it. So, then it should be fine to keep it as is?

**Comment by jensljungblad** [comment]
If the main benefit was speedier integration tests, then yeah, I guess we can skip this. Provided people write their integration tests with capybara, but I'm guessing most people do.

**Comment by Linuus** [comment]
Well, this is only an issue if we still want it to look like a link. Bootstrap does support buttons in navbars:
http://getbootstrap.com/components/#navbar-buttons

I'm fine with it looking like a bootstrap button instead of a link. It's probably more intuitive anyway.

**Comment by jensljungblad** [comment]
This PR was for the button group in the table though, and bootstrap does not support buttons in those. Basically this is what the css looks like:

```css
.btn-group > .btn {}
```

**Comment by Linuus** [comment]
Ah sorry. My bad :)

**Comment by jensljungblad** [comment]
Seems we reached the conclusion a) not possible with current bootstrap classes b) not strictly needed for integration test performance reasons, since capybara already supports `data-method` links. So I'll close this for now.

**Pull request closed without merging**
