### PR TITLE
Adds integration tests with capybara

### PR DESCRIPTION
**Pull request by jensljungblad**
- [x] Fix `File.join(engine_wrapper.namespaced_path, ...)` issues with leading `/`. Test that generators are working properly, the ones with `require_dependency` etc.
- [x] Dummy app with admin namespace with tests?
- [x] Dummy app with working assets
- [x] Capybara and template overrides doesn't seem to be working.. It works if we change prepend_view_path to append_view_path so that Rails does the overriding. Somehow our resolvers stop working inside the test.
- [x] Add test coverage with code climate

### CODE REVIEW

**Comment by jensljungblad** [comment]
Shouldn't this fix https://github.com/varvet/godmin/issues/104 since we now let Rails resolvers go first?

**Comment by Linuus** [comment]
If that is how Rails work by default, I guess so. I have not tested it though :)

**Comment by jensljungblad** [comment]
@Linuus Configured travis and code climate test coverage as well. Ready to merge this?

**Comment by Linuus** [comment]
@jensljungblad Do it! :+1: 
Good job!

**Pull request merged**
