### PR TITLE
Add titles to action links

### PR DESCRIPTION
**Pull request by ramhoj**
This is not only good for the visually impaired but also good for RackTest :).

### CODE REVIEW

**Comment by jensljungblad** [comment]
Nice! How come we need new translations? Can't we use `actions.show` instead of `actions.show_title` etc?

If we do need new ones, we should probably try and fix the other locales as well.

**Comment by ramhoj** [comment]
Since we want the title to include the name of the resource as well. I'm no export in screen-readers but I expect that if all the links just say's "show", "edit" etc it will be hard to know which one to click?

I missed that you there was more locales than en. Feel free to wait with merging this until I've copied the translations for those.

**Comment by jensljungblad** [comment]
Aha, yeah that makes sense. Sure, I'll let you do the translating stuff first :+1:

**Comment by ramhoj** [comment]
@jensljungblad I get like one miljon sass warnings on Travis. Do you think this has something to do with the commit in this PR?

**Comment by jensljungblad** [comment]
Wow, yeah that looks insane.. No idea, perhaps a gem that gets built with a weird version or something? Doesn't look like this PR contains anything that would cause it.

**Comment by jensljungblad** [comment]
We have a Swedish locale file as well btw :smile:

**Comment by jensljungblad** [comment]
I just restarted a build on a different PR and it fails with the same errors (https://travis-ci.org/varvet/godmin/jobs/113358426) so it's not this PR that causes it

**Comment by Linuus** [comment]
The issue with the CI is caused by Rake.
Fix: https://github.com/varvet/godmin/pull/191

**Pull request merged**
