### PR TITLE
Intro

### PR DESCRIPTION
**Pull request by jensljungblad**
So we should write something for the README that explains a bit about:

1. What Godmin is
2. Why Godmin should be used

### CODE REVIEW

**Comment by jensljungblad** [comment]
I think the nice thing about Godmin compared with other admin gems is that it's not really a DSL. You build it just like a normal Rails app with controllers, views, routes etc.

**Comment by jensljungblad** [comment]
**Here's something:**

Godmin is an admin framework for Rails 4+.

0a) It helps you create dedicated admin sections for your apps.

0b) It can be used to build stand alone admin apps, such as internal tools, or dedicated admin sections for regular apps.

It has support for common features such as scoping, filtering and performing batch actions on your models.

1a) While similar on the surface to tools like x and y, Godmin has a different approach to creating admin sections.

1b) Godmin differs from tools like x and y in how admin sections are created.

Rather than being a pure DSL, Godmin is a set of modules and helpers that can be applied to regular Rails apps and engines. An admin section built with Godmin is just that, a regular Rails app or Rails engine, with regular routes, controllers and views. That means it's less to learn because you already know most of it, and it's more flexible because the only limits are the limits imposed by Rails. After all, administrators are users too, and what better way to provide them with a tailor made experience than building them a Rails app?

**Comment by Linuus** [comment]
Some notes.
- Flexible, can override actions, views whatever like a normal rails app.
- Some opt-in features, such as Authentication and Authorization.
- Minimal inheritance, uses modules instead.

**Comment by juliaramstedt** [comment]
0c) Use it to build dedicated admin sections for your apps, or stand alone admin apps such as internal tools. (primary use case first, and more definitive and "It can be used for...")

**Comment by jensljungblad** [comment]
**Update**

Godmin is an admin framework for Rails 4+. Use it to build dedicated admin sections for your apps, or stand alone admin apps such as internal tools. It has support for common features such as scoping, filtering and performing batch actions on your models.

Godmin differs from tools like [ActiveAdmin](http://activeadmin.info/) and [RailsAdmin](https://github.com/sferik/rails_admin) in how admin sections are created. Rather than being DSL-based, Godmin is a set of opt-in modules and helpers that can be applied to regular Rails apps and engines. An admin section built with Godmin is just that, a regular Rails app or Rails engine, with regular routes, controllers and views. That means there is less to learn, because you already know most of it, and fewer constraints on what you can do. After all, administrators are users too, and what better way to provide them with a tailor made experience than building them a Rails app?

ping @Linuus @juliaramstedt

**Comment by jensljungblad** [comment]
Merge?

**Comment by Linuus** [comment]
:+1:

**Pull request merged**
